"""
Vision Banana backend implementation of PromptToSegment.

Instead of using a separate segmentation model, this backend prompts a
vision-language image-generation model (via LiteLLM) to *generate* a
colour-coded segmentation mask image directly, then decodes the mask by
clustering pixels whose colours match the per-instance colours that the
model was asked to paint.

This mirrors the approach described in the Vision Banana paper
(arXiv:2604.20329): each instance is rendered in a unique solid colour on
a black background, and masks are recovered by thresholding in RGB space.
"""
from __future__ import annotations

import base64
import re
import time
import urllib.request

import cv2
import numpy as np
import litellm

from .prompt_to_segment import LiteLLMClient, PromptToSegment, SegmentDebug, SegmentResult, draw_bboxes


# ---------------------------------------------------------------------------
# Palette used when asking the model to colour each instance
# Chosen to be visually distinct and well-separated in RGB space so that
# pixel-colour clustering is reliable.
# ---------------------------------------------------------------------------
_INSTANCE_COLOURS: list[tuple[int, int, int]] = [
    (255,   0,   0),   # pure red
    (  0, 255,   0),   # pure green
    (  0,   0, 255),   # pure blue
    (255, 255,   0),   # yellow
    (255,   0, 255),   # magenta
    (  0, 255, 255),   # cyan
    (255, 128,   0),   # orange
    (128,   0, 255),   # violet
    (  0, 255, 128),   # spring green
    (255,   0, 128),   # rose
    (128, 255,   0),   # chartreuse
    (  0, 128, 255),   # azure
]

_BACKGROUND_COLOUR: tuple[int, int, int] = (0, 0, 0)  # black

# How close (L∞ distance in RGB) a pixel must be to a palette colour to be
# assigned to that instance.  Generative models won't hit exact RGB values,
# so we need a tolerance band.
_COLOUR_TOLERANCE: int = 40

# Minimum number of pixels a colour cluster must contain to be kept.
_MIN_CLUSTER_PX: int = 150


def _build_colour_spec(n: int) -> str:
    """
    Return a human-readable colour spec for *n* instances, e.g.:
        Instance 1: RGB(255, 0, 0)
        Instance 2: RGB(0, 255, 0)
        ...
    """
    lines = []
    for i in range(n):
        r, g, b = _INSTANCE_COLOURS[i % len(_INSTANCE_COLOURS)]
        lines.append(f"  Instance {i + 1}: RGB({r}, {g}, {b})")
    return "\n".join(lines)


def _masks_from_generated_image(
    seg_image: np.ndarray,
    n_instances: int,
) -> list[tuple[int, np.ndarray]]:
    """
    Recover per-instance boolean masks from a generated segmentation image.

    Parameters
    ----------
    seg_image
        ``(H, W, 3)`` uint8 RGB array — the image generated by the model.
    n_instances
        Number of instances (colours) the model was asked to paint.

    Returns
    -------
    List of ``(instance_index, mask)`` pairs (0-based), skipping colours
    whose cluster is too small to be meaningful.
    """
    results = []
    seg = seg_image.astype(np.int32)  # avoid uint8 overflow in distance calc

    for i in range(n_instances):
        r, g, b = _INSTANCE_COLOURS[i % len(_INSTANCE_COLOURS)]
        target = np.array([r, g, b], dtype=np.int32)

        # L∞ distance: max absolute difference across channels
        diff = np.abs(seg - target).max(axis=-1)
        mask = diff <= _COLOUR_TOLERANCE

        if mask.sum() < _MIN_CLUSTER_PX:
            continue

        results.append((i, mask.astype(bool)))

    return results


class VisionBananaSegmentor(PromptToSegment):
    """
    Vision Banana-style segmentor: asks an image-generation / VLM model to
    *draw* a colour-coded instance segmentation mask, then decodes it.

    The model is prompted to output a plain RGB image where the background is
    black and each instance of the target object is filled with a specific
    pre-assigned colour.  Masks are extracted by thresholding pixel colours.

    Because the model chooses how many instances it sees, ``max_instances``
    acts as an upper bound on the palette; the actual count comes from which
    colour clusters are non-empty in the response image.

    Parameters
    ----------
    llm_client
        ``LiteLLMClient`` pointing at any LiteLLM-compatible multimodal model
        that can both accept an input image and return an output image
        (e.g. a Vision Banana checkpoint served via a compatible API).
    max_instances
        Maximum number of distinct instances the model will be asked to label.
    colour_tolerance
        L∞ tolerance in RGB for assigning pixels to a palette colour.
    min_cluster_px
        Minimum pixel count for a colour cluster to be kept as a mask.
    """

    def __init__(
        self,
        llm_client: LiteLLMClient,
        max_instances: int = 8,
        colour_tolerance: int = _COLOUR_TOLERANCE,
        min_cluster_px: int = _MIN_CLUSTER_PX,
    ) -> None:
        # Pass llm_client to base but we override the full segment() flow
        super().__init__(llm_client=llm_client)
        self._max_instances = max_instances
        self._colour_tolerance = colour_tolerance
        self._min_cluster_px = min_cluster_px

    # ------------------------------------------------------------------
    # PromptToSegment interface
    # ------------------------------------------------------------------

    def generate_masks(
        self, rgb_image: np.ndarray, prompt: str
    ) -> tuple[list[np.ndarray], list[float]]:
        """
        Ask the model to generate a colour-coded segmentation image, then
        decode it into boolean masks.

        Returns masks sorted by cluster size (largest first), with uniform
        scores of 1.0 (the model doesn't emit per-mask confidences).
        """
        seg_image = self._query_model_for_seg_image(rgb_image, prompt)
        if seg_image is None:
            return [], []

        clusters = _masks_from_generated_image(seg_image, self._max_instances)

        # Sort largest → smallest
        clusters.sort(key=lambda t: t[1].sum(), reverse=True)

        masks = [mask for _, mask in clusters]
        scores = [1.0] * len(masks)
        return masks, scores

    def segment(self, rgb_image: np.ndarray, prompt: str) -> list[SegmentResult]:
        """
        Full pipeline: generate segmentation image → decode masks → build results.
        """
        t_total = time.perf_counter()
        t_seg = time.perf_counter()
        masks, _ = self.generate_masks(rgb_image, prompt)
        segmentation_time = time.perf_counter() - t_seg

        results: list[SegmentResult] = []
        for idx, mask in enumerate(masks):
            ys, xs = np.where(mask)
            centroid_px = (int(xs.mean()), int(ys.mean()))
            results.append(SegmentResult(
                mask=mask,
                centroid_px=centroid_px,
                mask_ids=[idx],
            ))

        self.debug = SegmentDebug(
            vlm_text_prompt=prompt,
            vlm_input_image=rgb_image,
            segmentation_time_s=segmentation_time,
            inference_time_s=time.perf_counter() - t_total,
        )
        return results

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_segmentation_prompt(self, prompt: str) -> str:
        colour_spec = _build_colour_spec(self._max_instances)
        return (
            f"Generate an instance segmentation mask image for the following object: {prompt}.\n\n"
            "Output a plain RGB image with the SAME dimensions as the input image.\n"
            "Rules:\n"
            f"- Background (everything that is NOT '{prompt}'): RGB(0, 0, 0) — pure black.\n"
            f"- Each separate physical instance of '{prompt}' must be filled with a "
            "SOLID, UNIFORM colour taken from the list below.  Use a different colour "
            "for each instance.  Do NOT mix colours within one instance.\n"
            f"- Do NOT draw outlines, shadows, gradients, or any texture — solid fill only.\n"
            f"Colour assignments:\n{colour_spec}\n\n"
            "If there are no instances of the object, output a completely black image.\n"
            "Output ONLY the mask image — no text, no explanation."
        )

    def _image_to_base64(self, image: np.ndarray) -> str:
        bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        ok, buf = cv2.imencode(".jpg", bgr, [cv2.IMWRITE_JPEG_QUALITY, 95])
        if not ok:
            raise RuntimeError("cv2.imencode failed")
        return base64.b64encode(buf.tobytes()).decode("utf-8")

    def _response_to_image(self, response) -> np.ndarray | None:
        """
        Extract the generated image from a LiteLLM response.

        Handles:
        1. Content list with an image_url block (data URI)
        2. Markdown embedded image: ![...](data:image/...;base64,...)
        3. Markdown image with external URL: ![...](https://...)
        4. HTML <img src="data:image/...;base64,...">
        5. Raw base64 string
        """
        choice = response.choices[0]
        msg = choice.message
        content = msg.content

        # Shape 0: LiteLLM message.images — populated when the model emits image output
        # Each entry looks like {'image_url': {'url': 'data:image/jpeg;base64,...'}}
        images = getattr(msg, 'images', None)
        if images:
            for img in images:
                if isinstance(img, dict):
                    url = (img.get('image_url') or {}).get('url', '')
                    if url.startswith('data:image'):
                        return self._b64_to_numpy(url.split(',', 1)[1])
                    b64 = img.get('b64_json') or img.get('data')
                    if b64:
                        return self._b64_to_numpy(b64)
                elif isinstance(img, str):
                    try:
                        return self._b64_to_numpy(img)
                    except Exception:
                        pass

        # Shape 1: content is a list of blocks
        if isinstance(content, list):
            for block in content:
                if isinstance(block, dict):
                    url = (block.get("image_url") or {}).get("url", "")
                    if url.startswith("data:image"):
                        b64 = url.split(",", 1)[1]
                        return self._b64_to_numpy(b64)

        if isinstance(content, str):
            stripped = content.strip()

            # Shape 2: markdown image with embedded data URI
            md_match = re.search(r'!\[.*?\]\(data:image/[^;]+;base64,([A-Za-z0-9+/=]+)\)', stripped)
            if md_match:
                return self._b64_to_numpy(md_match.group(1))

            # Shape 3: markdown image with external URL — download it
            md_url_match = re.search(r'!\[.*?\]\((https?://[^)]+)\)', stripped)
            if md_url_match:
                url = md_url_match.group(1)
                try:
                    req = urllib.request.Request(
                        url, headers={"User-Agent": "Mozilla/5.0"}
                    )
                    with urllib.request.urlopen(req, timeout=10) as resp:
                        data = resp.read()
                    arr = np.frombuffer(data, dtype=np.uint8)
                    return cv2.cvtColor(cv2.imdecode(arr, cv2.IMREAD_COLOR), cv2.COLOR_BGR2RGB)
                except Exception:
                    pass

            # Shape 4: HTML <img> with data URI
            html_match = re.search(r'src=["\']data:image/[^;]+;base64,([A-Za-z0-9+/=]+)["\']', stripped)
            if html_match:
                return self._b64_to_numpy(html_match.group(1))

            # Shape 5: raw base64 string
            try:
                return self._b64_to_numpy(stripped)
            except Exception:
                pass

            return None

        return None

    @staticmethod
    def _b64_to_numpy(b64: str) -> np.ndarray:
        arr = np.frombuffer(base64.b64decode(b64), dtype=np.uint8)
        return cv2.cvtColor(cv2.imdecode(arr, cv2.IMREAD_COLOR), cv2.COLOR_BGR2RGB)

    def _query_model_for_seg_image(
        self, rgb_image: np.ndarray, prompt: str
    ) -> np.ndarray | None:
        """
        Send the input image + segmentation prompt to the model and return
        the generated segmentation image as a numpy RGB array, or None on
        failure.
        """
        seg_prompt = self._build_segmentation_prompt(prompt)
        b64_input = self._image_to_base64(rgb_image)

        response = litellm.completion(
            model=self._llm.model,
            api_base=self._llm.api_base,
            api_key=self._llm.api_key,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{b64_input}"},
                        },
                        {
                            "type": "text",
                            "text": seg_prompt,
                        },
                    ],
                }
            ],
        )

        seg_image = self._response_to_image(response)
        if seg_image is None:
            return None
        # Resize to match input if the model returned a different resolution
        h, w = rgb_image.shape[:2]
        if seg_image.shape[:2] != (h, w):
            seg_image = cv2.resize(seg_image, (w, h), interpolation=cv2.INTER_NEAREST)

        return seg_image


class VisionBananaBboxSegmentor(VisionBananaSegmentor):
    """
    Vision Banana variant that uses coordinate/bbox grounding.

    A reasoning VLM (llm_client) predicts bounding boxes via segment_by_coord.
    All boxes are overlaid on the full image at once and sent to an image-generation
    model (image_gen_client), which paints the object inside each box with a distinct
    solid colour.  Masks are recovered by the same colour-cluster decoding used in
    VisionBananaSegmentor.

    Parameters
    ----------
    llm_client
        Reasoning VLM used by segment_by_coord to predict bounding boxes.
    image_gen_client
        Image-generation model that produces the colour-coded mask image.
    colour_tolerance
        L∞ tolerance in RGB for assigning pixels to a palette colour.
    min_cluster_px
        Minimum pixel count for a colour cluster to be kept as a mask.
    """

    def __init__(
        self,
        llm_client: LiteLLMClient,
        image_gen_client: LiteLLMClient,
        colour_tolerance: int = _COLOUR_TOLERANCE,
        min_cluster_px: int = _MIN_CLUSTER_PX,
    ) -> None:
        super().__init__(
            llm_client=llm_client,
            colour_tolerance=colour_tolerance,
            min_cluster_px=min_cluster_px,
        )
        self._image_gen = image_gen_client

    # ------------------------------------------------------------------
    # PromptToSegment interface
    # ------------------------------------------------------------------

    def segment(self, rgb_image: np.ndarray, prompt: str) -> list[SegmentResult]:
        return self.segment_by_coord(rgb_image, prompt)

    def generate_masks_from_bbox(
        self,
        rgb_image: np.ndarray,
        boxes: list[tuple[float, float, float, float]],
    ) -> tuple[list[np.ndarray], list[float]]:
        """
        Overlay all boxes on the full image, query the image generator once,
        then decode one mask per box from the returned colour-coded image.
        """
        annotated = draw_bboxes(rgb_image, boxes, colours=_INSTANCE_COLOURS, index_offset=1, font_scale=0.8)
        seg_prompt = self._build_bbox_seg_prompt(len(boxes))

        seg_image = self._query_image_gen(annotated, rgb_image.shape[:2], seg_prompt)

        if seg_image is None:
            return [], []

        masks: list[np.ndarray] = []
        scores: list[float] = []
        for i in range(len(boxes)):
            r, g, b = _INSTANCE_COLOURS[i % len(_INSTANCE_COLOURS)]
            target = np.array([r, g, b], dtype=np.int32)
            diff = np.abs(seg_image.astype(np.int32) - target).max(axis=-1)
            mask = (diff <= self._colour_tolerance).astype(bool)
            if mask.sum() >= self._min_cluster_px:
                masks.append(mask)
                scores.append(1.0)

        return masks, scores

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_bbox_seg_prompt(self, n_boxes: int) -> str:
        colour_spec = _build_colour_spec(n_boxes)
        return (
            "Generate an instance segmentation mask image.\n\n"
            "Output a plain RGB image with the SAME dimensions as the input image.\n"
            "Rules:\n"
            "- Background (everything that is NOT the object inside a numbered bounding box): "
            "RGB(0, 0, 0) — pure black.\n"
            "- For each numbered bounding box drawn on the image, fill ONLY the object "
            "inside that box with the corresponding SOLID, UNIFORM colour from the list below.  "
            "Do NOT mix colours within one box.  Do NOT paint the box border itself.\n"
            "- Do NOT draw outlines, shadows, gradients, or any texture — solid fill only.\n"
            f"Colour assignments (box number → fill colour):\n{colour_spec}\n\n"
            "If a box contains no recognisable object, leave that region black.\n"
            "Output ONLY the mask image — no text, no explanation."
        )

    def _query_image_gen(
        self,
        annotated_image: np.ndarray,
        original_shape: tuple[int, int],
        seg_prompt: str,
    ) -> np.ndarray | None:
        """Send the box-annotated image to the image generator; return the decoded mask."""
        b64 = self._image_to_base64(annotated_image)

        response = litellm.completion(
            model=self._image_gen.model,
            api_base=self._image_gen.api_base,
            api_key=self._image_gen.api_key,
            messages=[{
                "role": "user",
                "content": [
                    {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{b64}"}},
                    {"type": "text", "text": seg_prompt},
                ],
            }],
        )

        seg_image = self._response_to_image(response)
        if seg_image is None:
            return None

        h, w = original_shape
        if seg_image.shape[:2] != (h, w):
            seg_image = cv2.resize(seg_image, (w, h), interpolation=cv2.INTER_NEAREST)
        return seg_image