services:
  build:
    image: ${PROJECT_NAME}:${BASE_IMAGE}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - VIRTUALGL_VER=${VIRTUALGL_VER:-3.1}
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
        - BASE_IMAGE=${BASE_IMAGE}
        - DOCKER_ROS_DISTRO=${DOCKER_ROS_DISTRO:-jazzy}
        - DOCKER_RMW_IMPLEMENTATION=${DOCKER_RMW_IMPLEMENTATION}
        - WORKSPACE_NAME=${WORKSPACE_NAME:-ros2_ws}
        - HF_TOKEN=${HF_TOKEN}
      target: final

  base:
    image: ${PROJECT_NAME}:${BASE_IMAGE}
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - GPU_ID=${GPU_ID:-0}
      - ROS_DOMAIN_ID=${DOCKER_ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${DOCKER_RMW_IMPLEMENTATION}
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/ros/.Xauthority

  bringup:
    container_name: bringup
    extends: base
    command: ros2 launch xarm_moveit_config lite6_moveit_${BRINGUP_MODE:-realmove}.launch.py robot_ip:=192.168.1.151 add_gripper:=true
    volumes:
      - ../xarm_ros2/xarm_moveit_config/launch/_robot_moveit_common2.launch.py:/home/ros/ros2_ws/install/xarm_moveit_config/share/xarm_moveit_config/launch/_robot_moveit_common2.launch.py:ro

  realsense:
    container_name: realsense
    extends: base
    command: ros2 launch realsense2_camera rs_launch.py align_depth.enable:=true
    volumes:
      - ../:/home/ros/${WORKSPACE_NAME:-ros2_ws}/src/

  camera-joint-state-publisher:
    container_name: camera-joint-state-publisher
    extends: base
    command: ros2 run manipulation_perception camera_joint_state_publisher

  dev:
    container_name: dev
    extends: base
    command: sleep infinity
    volumes:
      - ../:/home/ros/${WORKSPACE_NAME:-ros2_ws}/src/
    devices:
      - /dev/bus/usb:/dev/bus/usb

  kasmvnc:
    container_name: kasmvnc
    image: lsiobase/kasmvnc:alpine321
    network_mode: host
    environment:
    - DISPLAY=:200
    volumes:
    - ./kasm-autostart:/defaults/autostart
